language: node_js
node_js:
  - 16
before_install:
  - printf "\n" >> ~/.npmrc
  - curl -u $NPM_USERNAME:$NPM_PASSWORD https://na.artifactory.swg-devops.com/artifactory/api/npm/hyc-aspera-ui-team-npm-local/auth/aspera-ui >> ~/.npmrc
  - curl -u $NPM_ASPERA_USERNAME:$NPM_ASPERA_PASSWORD https://na.artifactory.swg-devops.com/artifactory/api/npm/hyc-aspera-team-npm-virtual/auth/aspera >> ~/.npmrc
stages:
  - lint
  - test
  - docs
  - name: pages
    if: branch = main
  - name: release
    if: branch = main
  - name: build
    if: branch = main
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
    - stage: docs
      script: npm run docs
    - stage: pages
      script: npm run build:demo
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        github_url: github.ibm.com
        keep_history: false
        local_dir: dist/js
        on:
          branch: main
    - stage: release
      script: git checkout main && npm run release -- --no-verify && git push --follow-tags origin main
    - stage: build
      script: git checkout main && git pull origin main && npm run build:deploy
