name: Documentation

on:
  push:
    branches:
      - main

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install
        run: |
          npm ci

      - name: Build Package
        run: |
          npm run build

      - name: Build Documentation
        run: |
          npm run docs
          cp src/index.html dist/js
          cp -R sdk-docs dist/js/docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist/js
